version: '3.6'

services:

  generator:
    build:
      context: ./services/generator
      dockerfile: Dockerfile-prod
    expose:
      - '5000'
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - APP_SETTINGS=project.config.ProductionConfig
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8

  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - generator
